stages:
  - build
  - deploy

variables:
  REGISTRY: cr.yandex

# ---------- BUILD SERVER ----------
build_server:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"oauth\",\"password\":\"$YC_TOKEN\"}}}" > /kaniko/.docker/config.json

    - /kaniko/executor
      --context $CI_PROJECT_DIR/server
      --dockerfile $CI_PROJECT_DIR/server/Dockerfile
      --destination $REGISTRY/$REGISTRY_ID/server:$CI_COMMIT_SHORT_SHA
      --destination $REGISTRY/$REGISTRY_ID/server:latest
  only:
    - main

# ---------- BUILD CLIENT ----------
build_client:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:latest
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY\":{\"username\":\"oauth\",\"password\":\"$YC_TOKEN\"}}}" > /kaniko/.docker/config.json

    - /kaniko/executor
      --context $CI_PROJECT_DIR/client
      --dockerfile $CI_PROJECT_DIR/client/Dockerfile
      --destination $REGISTRY/$REGISTRY_ID/client:$CI_COMMIT_SHORT_SHA
      --destination $REGISTRY/$REGISTRY_ID/client:latest
  only:
    - main

# ---------- DEPLOY ----------
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl set image deployment/server server=$REGISTRY/$REGISTRY_ID/server:$CI_COMMIT_SHORT_SHA
    - kubectl set image deployment/client client=$REGISTRY/$REGISTRY_ID/client:$CI_COMMIT_SHORT_SHA
  only:
    - main